/**
 * Problem Data Library
 *
 * Hardcoded problem library for MVP.
 * Contains 25 linear equation problems with varying difficulty.
 */

import { Problem, ProblemCategory, ProblemDifficulty } from '../types/Problem';

/**
 * Linear equation problems library
 * 15 easy + 25 medium + 30 hard + 10 very hard = 80 total problems
 */
export const LINEAR_EQUATION_PROBLEMS: Problem[] = [
  // ==================== EASY - One-step equations (15 problems) ====================
  {
    id: 'le_easy_01',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: x + 5 = 12',
    latex: 'x + 5 = 12',
    answer: '7',
    answerLatex: 'x = 7',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 5 from both sides',
        expression: 'x + 5 - 5 = 12 - 5',
        operation: 'subtract 5 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 7',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'addition'],
  },
  {
    id: 'le_easy_02',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: x - 8 = 3',
    latex: 'x - 8 = 3',
    answer: '11',
    answerLatex: 'x = 11',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 8 to both sides',
        expression: 'x - 8 + 8 = 3 + 8',
        operation: 'add 8 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 11',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'subtraction'],
  },
  {
    id: 'le_easy_03',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: 3x = 15',
    latex: '3x = 15',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{15}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'multiplication'],
  },
  {
    id: 'le_easy_04',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: x/4 = 2',
    latex: '\\frac{x}{4} = 2',
    answer: '8',
    answerLatex: 'x = 8',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Multiply both sides by 4',
        expression: '4 \\cdot \\frac{x}{4} = 2 \\cdot 4',
        operation: 'multiply both sides by 4',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 8',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'division'],
  },
  {
    id: 'le_easy_05',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: 2x = 18',
    latex: '2x = 18',
    answer: '9',
    answerLatex: 'x = 9',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{18}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 9',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'multiplication'],
  },
  {
    id: 'le_easy_06',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: x + 12 = 20',
    latex: 'x + 12 = 20',
    answer: '8',
    answerLatex: 'x = 8',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 12 from both sides',
        expression: 'x + 12 - 12 = 20 - 12',
        operation: 'subtract 12 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 8',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'addition'],
  },
  {
    id: 'le_easy_07',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: x - 15 = 7',
    latex: 'x - 15 = 7',
    answer: '22',
    answerLatex: 'x = 22',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 15 to both sides',
        expression: 'x - 15 + 15 = 7 + 15',
        operation: 'add 15 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 22',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'subtraction'],
  },
  {
    id: 'le_easy_08',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: 5x = 30',
    latex: '5x = 30',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{30}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'multiplication'],
  },
  {
    id: 'le_easy_09',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: x/6 = 3',
    latex: '\\frac{x}{6} = 3',
    answer: '18',
    answerLatex: 'x = 18',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Multiply both sides by 6',
        expression: '6 \\cdot \\frac{x}{6} = 3 \\cdot 6',
        operation: 'multiply both sides by 6',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 18',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'division'],
  },
  {
    id: 'le_easy_10',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: 7x = 49',
    latex: '7x = 49',
    answer: '7',
    answerLatex: 'x = 7',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Divide both sides by 7',
        expression: '\\frac{7x}{7} = \\frac{49}{7}',
        operation: 'divide both sides by 7',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 7',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'multiplication'],
  },
  {
    id: 'le_easy_11',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: x + 9 = 15',
    latex: 'x + 9 = 15',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 9 from both sides',
        expression: 'x + 9 - 9 = 15 - 9',
        operation: 'subtract 9 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'addition'],
  },
  {
    id: 'le_easy_12',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: x - 6 = 10',
    latex: 'x - 6 = 10',
    answer: '16',
    answerLatex: 'x = 16',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 6 to both sides',
        expression: 'x - 6 + 6 = 10 + 6',
        operation: 'add 6 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 16',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'subtraction'],
  },
  {
    id: 'le_easy_13',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: 4x = 28',
    latex: '4x = 28',
    answer: '7',
    answerLatex: 'x = 7',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Divide both sides by 4',
        expression: '\\frac{4x}{4} = \\frac{28}{4}',
        operation: 'divide both sides by 4',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 7',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'multiplication'],
  },
  {
    id: 'le_easy_14',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: x/5 = 4',
    latex: '\\frac{x}{5} = 4',
    answer: '20',
    answerLatex: 'x = 20',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Multiply both sides by 5',
        expression: '5 \\cdot \\frac{x}{5} = 4 \\cdot 5',
        operation: 'multiply both sides by 5',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 20',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'division'],
  },
  {
    id: 'le_easy_15',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.EASY,
    text: 'Solve for x: 6x = 42',
    latex: '6x = 42',
    answer: '7',
    answerLatex: 'x = 7',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Divide both sides by 6',
        expression: '\\frac{6x}{6} = \\frac{42}{6}',
        operation: 'divide both sides by 6',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x = 7',
        operation: 'simplify',
      },
    ],
    tags: ['one-step', 'multiplication'],
  },

  // ==================== MEDIUM - Two-step equations (25 problems) ====================
  {
    id: 'le_medium_01',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 2x + 3 = 11',
    latex: '2x + 3 = 11',
    answer: '4',
    answerLatex: 'x = 4',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 3 from both sides',
        expression: '2x + 3 - 3 = 11 - 3',
        operation: 'subtract 3 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '2x = 8',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{8}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 4',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'addition', 'multiplication'],
  },
  {
    id: 'le_medium_02',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 5x - 7 = 18',
    latex: '5x - 7 = 18',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 7 to both sides',
        expression: '5x - 7 + 7 = 18 + 7',
        operation: 'add 7 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'subtraction', 'multiplication'],
  },
  {
    id: 'le_medium_03',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 3x + 4 = 19',
    latex: '3x + 4 = 19',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 4 from both sides',
        expression: '3x + 4 - 4 = 19 - 4',
        operation: 'subtract 4 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '3x = 15',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{15}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'addition', 'multiplication'],
  },
  {
    id: 'le_medium_04',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: x/2 + 5 = 9',
    latex: '\\frac{x}{2} + 5 = 9',
    answer: '8',
    answerLatex: 'x = 8',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 5 from both sides',
        expression: '\\frac{x}{2} + 5 - 5 = 9 - 5',
        operation: 'subtract 5 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '\\frac{x}{2} = 4',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Multiply both sides by 2',
        expression: '2 \\cdot \\frac{x}{2} = 4 \\cdot 2',
        operation: 'multiply both sides by 2',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 8',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'division', 'addition'],
  },
  {
    id: 'le_medium_05',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 4x - 9 = 7',
    latex: '4x - 9 = 7',
    answer: '4',
    answerLatex: 'x = 4',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 9 to both sides',
        expression: '4x - 9 + 9 = 7 + 9',
        operation: 'add 9 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '4x = 16',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 4',
        expression: '\\frac{4x}{4} = \\frac{16}{4}',
        operation: 'divide both sides by 4',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 4',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'subtraction', 'multiplication'],
  },
  {
    id: 'le_medium_06',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 6x + 2 = 20',
    latex: '6x + 2 = 20',
    answer: '3',
    answerLatex: 'x = 3',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 2 from both sides',
        expression: '6x + 2 - 2 = 20 - 2',
        operation: 'subtract 2 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '6x = 18',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 6',
        expression: '\\frac{6x}{6} = \\frac{18}{6}',
        operation: 'divide both sides by 6',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 3',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'addition', 'multiplication'],
  },
  {
    id: 'le_medium_07',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: x/3 - 4 = 2',
    latex: '\\frac{x}{3} - 4 = 2',
    answer: '18',
    answerLatex: 'x = 18',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 4 to both sides',
        expression: '\\frac{x}{3} - 4 + 4 = 2 + 4',
        operation: 'add 4 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '\\frac{x}{3} = 6',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Multiply both sides by 3',
        expression: '3 \\cdot \\frac{x}{3} = 6 \\cdot 3',
        operation: 'multiply both sides by 3',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 18',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'division', 'subtraction'],
  },
  {
    id: 'le_medium_08',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 7x - 5 = 16',
    latex: '7x - 5 = 16',
    answer: '3',
    answerLatex: 'x = 3',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 5 to both sides',
        expression: '7x - 5 + 5 = 16 + 5',
        operation: 'add 5 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '7x = 21',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 7',
        expression: '\\frac{7x}{7} = \\frac{21}{7}',
        operation: 'divide both sides by 7',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 3',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'subtraction', 'multiplication'],
  },
  {
    id: 'le_medium_09',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 8x + 1 = 25',
    latex: '8x + 1 = 25',
    answer: '3',
    answerLatex: 'x = 3',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 1 from both sides',
        expression: '8x + 1 - 1 = 25 - 1',
        operation: 'subtract 1 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '8x = 24',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 8',
        expression: '\\frac{8x}{8} = \\frac{24}{8}',
        operation: 'divide both sides by 8',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 3',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'addition', 'multiplication'],
  },
  {
    id: 'le_medium_10',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: x/5 + 3 = 7',
    latex: '\\frac{x}{5} + 3 = 7',
    answer: '20',
    answerLatex: 'x = 20',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 3 from both sides',
        expression: '\\frac{x}{5} + 3 - 3 = 7 - 3',
        operation: 'subtract 3 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '\\frac{x}{5} = 4',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Multiply both sides by 5',
        expression: '5 \\cdot \\frac{x}{5} = 4 \\cdot 5',
        operation: 'multiply both sides by 5',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 20',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'division', 'addition'],
  },
  {
    id: 'le_medium_11',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 9x + 5 = 50',
    latex: '9x + 5 = 50',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 5 from both sides',
        expression: '9x + 5 - 5 = 50 - 5',
        operation: 'subtract 5 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '9x = 45',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 9',
        expression: '\\frac{9x}{9} = \\frac{45}{9}',
        operation: 'divide both sides by 9',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'addition', 'multiplication'],
  },
  {
    id: 'le_medium_12',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 10x - 8 = 42',
    latex: '10x - 8 = 42',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 8 to both sides',
        expression: '10x - 8 + 8 = 42 + 8',
        operation: 'add 8 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '10x = 50',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 10',
        expression: '\\frac{10x}{10} = \\frac{50}{10}',
        operation: 'divide both sides by 10',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'subtraction', 'multiplication'],
  },
  {
    id: 'le_medium_13',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: x/7 + 2 = 5',
    latex: '\\frac{x}{7} + 2 = 5',
    answer: '21',
    answerLatex: 'x = 21',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 2 from both sides',
        expression: '\\frac{x}{7} + 2 - 2 = 5 - 2',
        operation: 'subtract 2 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '\\frac{x}{7} = 3',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Multiply both sides by 7',
        expression: '7 \\cdot \\frac{x}{7} = 3 \\cdot 7',
        operation: 'multiply both sides by 7',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 21',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'division', 'addition'],
  },
  {
    id: 'le_medium_14',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 12x + 7 = 55',
    latex: '12x + 7 = 55',
    answer: '4',
    answerLatex: 'x = 4',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 7 from both sides',
        expression: '12x + 7 - 7 = 55 - 7',
        operation: 'subtract 7 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '12x = 48',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 12',
        expression: '\\frac{12x}{12} = \\frac{48}{12}',
        operation: 'divide both sides by 12',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 4',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'addition', 'multiplication'],
  },
  {
    id: 'le_medium_15',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: x/8 - 1 = 3',
    latex: '\\frac{x}{8} - 1 = 3',
    answer: '32',
    answerLatex: 'x = 32',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 1 to both sides',
        expression: '\\frac{x}{8} - 1 + 1 = 3 + 1',
        operation: 'add 1 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '\\frac{x}{8} = 4',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Multiply both sides by 8',
        expression: '8 \\cdot \\frac{x}{8} = 4 \\cdot 8',
        operation: 'multiply both sides by 8',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 32',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'division', 'subtraction'],
  },
  {
    id: 'le_medium_16',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 3x - 11 = 4',
    latex: '3x - 11 = 4',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 11 to both sides',
        expression: '3x - 11 + 11 = 4 + 11',
        operation: 'add 11 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '3x = 15',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{15}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'subtraction', 'multiplication'],
  },
  {
    id: 'le_medium_17',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 11x + 9 = 64',
    latex: '11x + 9 = 64',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 9 from both sides',
        expression: '11x + 9 - 9 = 64 - 9',
        operation: 'subtract 9 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '11x = 55',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 11',
        expression: '\\frac{11x}{11} = \\frac{55}{11}',
        operation: 'divide both sides by 11',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'addition', 'multiplication'],
  },
  {
    id: 'le_medium_18',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: x/6 + 7 = 12',
    latex: '\\frac{x}{6} + 7 = 12',
    answer: '30',
    answerLatex: 'x = 30',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 7 from both sides',
        expression: '\\frac{x}{6} + 7 - 7 = 12 - 7',
        operation: 'subtract 7 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '\\frac{x}{6} = 5',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Multiply both sides by 6',
        expression: '6 \\cdot \\frac{x}{6} = 5 \\cdot 6',
        operation: 'multiply both sides by 6',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 30',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'division', 'addition'],
  },
  {
    id: 'le_medium_19',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 15x - 12 = 33',
    latex: '15x - 12 = 33',
    answer: '3',
    answerLatex: 'x = 3',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 12 to both sides',
        expression: '15x - 12 + 12 = 33 + 12',
        operation: 'add 12 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '15x = 45',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 15',
        expression: '\\frac{15x}{15} = \\frac{45}{15}',
        operation: 'divide both sides by 15',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 3',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'subtraction', 'multiplication'],
  },
  {
    id: 'le_medium_20',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: x/9 - 2 = 1',
    latex: '\\frac{x}{9} - 2 = 1',
    answer: '27',
    answerLatex: 'x = 27',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 2 to both sides',
        expression: '\\frac{x}{9} - 2 + 2 = 1 + 2',
        operation: 'add 2 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '\\frac{x}{9} = 3',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Multiply both sides by 9',
        expression: '9 \\cdot \\frac{x}{9} = 3 \\cdot 9',
        operation: 'multiply both sides by 9',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 27',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'division', 'subtraction'],
  },
  {
    id: 'le_medium_21',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 2x + 15 = 31',
    latex: '2x + 15 = 31',
    answer: '8',
    answerLatex: 'x = 8',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 15 from both sides',
        expression: '2x + 15 - 15 = 31 - 15',
        operation: 'subtract 15 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '2x = 16',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{16}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 8',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'addition', 'multiplication'],
  },
  {
    id: 'le_medium_22',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 13x - 6 = 46',
    latex: '13x - 6 = 46',
    answer: '4',
    answerLatex: 'x = 4',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 6 to both sides',
        expression: '13x - 6 + 6 = 46 + 6',
        operation: 'add 6 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '13x = 52',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 13',
        expression: '\\frac{13x}{13} = \\frac{52}{13}',
        operation: 'divide both sides by 13',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 4',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'subtraction', 'multiplication'],
  },
  {
    id: 'le_medium_23',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: x/10 + 4 = 9',
    latex: '\\frac{x}{10} + 4 = 9',
    answer: '50',
    answerLatex: 'x = 50',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 4 from both sides',
        expression: '\\frac{x}{10} + 4 - 4 = 9 - 4',
        operation: 'subtract 4 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '\\frac{x}{10} = 5',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Multiply both sides by 10',
        expression: '10 \\cdot \\frac{x}{10} = 5 \\cdot 10',
        operation: 'multiply both sides by 10',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 50',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'division', 'addition'],
  },
  {
    id: 'le_medium_24',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: 14x + 3 = 59',
    latex: '14x + 3 = 59',
    answer: '4',
    answerLatex: 'x = 4',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 3 from both sides',
        expression: '14x + 3 - 3 = 59 - 3',
        operation: 'subtract 3 from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '14x = 56',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Divide both sides by 14',
        expression: '\\frac{14x}{14} = \\frac{56}{14}',
        operation: 'divide both sides by 14',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 4',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'addition', 'multiplication'],
  },
  {
    id: 'le_medium_25',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.MEDIUM,
    text: 'Solve for x: x/12 - 3 = 2',
    latex: '\\frac{x}{12} - 3 = 2',
    answer: '60',
    answerLatex: 'x = 60',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Add 3 to both sides',
        expression: '\\frac{x}{12} - 3 + 3 = 2 + 3',
        operation: 'add 3 to both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '\\frac{x}{12} = 5',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Multiply both sides by 12',
        expression: '12 \\cdot \\frac{x}{12} = 5 \\cdot 12',
        operation: 'multiply both sides by 12',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 60',
        operation: 'simplify',
      },
    ],
    tags: ['two-step', 'division', 'subtraction'],
  },

  // ==================== HARD - Multi-step with variables on both sides (30 problems) ====================
  {
    id: 'le_hard_01',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 3x + 7 = 2x + 15',
    latex: '3x + 7 = 2x + 15',
    answer: '8',
    answerLatex: 'x = 8',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 2x from both sides',
        expression: '3x - 2x + 7 = 2x - 2x + 15',
        operation: 'subtract 2x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: 'x + 7 = 15',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 7 from both sides',
        expression: 'x + 7 - 7 = 15 - 7',
        operation: 'subtract 7 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x = 8',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_02',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 5x - 4 = 3x + 10',
    latex: '5x - 4 = 3x + 10',
    answer: '7',
    answerLatex: 'x = 7',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 3x from both sides',
        expression: '5x - 3x - 4 = 3x - 3x + 10',
        operation: 'subtract 3x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '2x - 4 = 10',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 4 to both sides',
        expression: '2x - 4 + 4 = 10 + 4',
        operation: 'add 4 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '2x = 14',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{14}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 7',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_03',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 4x + 9 = x + 24',
    latex: '4x + 9 = x + 24',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract x from both sides',
        expression: '4x - x + 9 = x - x + 24',
        operation: 'subtract x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '3x + 9 = 24',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 9 from both sides',
        expression: '3x + 9 - 9 = 24 - 9',
        operation: 'subtract 9 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '3x = 15',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{15}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_04',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 6x - 8 = 2x + 12',
    latex: '6x - 8 = 2x + 12',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 2x from both sides',
        expression: '6x - 2x - 8 = 2x - 2x + 12',
        operation: 'subtract 2x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '4x - 8 = 12',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 8 to both sides',
        expression: '4x - 8 + 8 = 12 + 8',
        operation: 'add 8 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '4x = 20',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 4',
        expression: '\\frac{4x}{4} = \\frac{20}{4}',
        operation: 'divide both sides by 4',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_05',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 7x + 3 = 4x + 18',
    latex: '7x + 3 = 4x + 18',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 4x from both sides',
        expression: '7x - 4x + 3 = 4x - 4x + 18',
        operation: 'subtract 4x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '3x + 3 = 18',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 3 from both sides',
        expression: '3x + 3 - 3 = 18 - 3',
        operation: 'subtract 3 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '3x = 15',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{15}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_06',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 2x + 11 = 5x - 7',
    latex: '2x + 11 = 5x - 7',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 2x from both sides',
        expression: '2x - 2x + 11 = 5x - 2x - 7',
        operation: 'subtract 2x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '11 = 3x - 7',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 7 to both sides',
        expression: '11 + 7 = 3x - 7 + 7',
        operation: 'add 7 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '18 = 3x',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 3',
        expression: '\\frac{18}{3} = \\frac{3x}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_07',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 8x - 5 = 3x + 20',
    latex: '8x - 5 = 3x + 20',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 3x from both sides',
        expression: '8x - 3x - 5 = 3x - 3x + 20',
        operation: 'subtract 3x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x - 5 = 20',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 5 to both sides',
        expression: '5x - 5 + 5 = 20 + 5',
        operation: 'add 5 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_08',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 9x + 2 = 6x + 17',
    latex: '9x + 2 = 6x + 17',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 6x from both sides',
        expression: '9x - 6x + 2 = 6x - 6x + 17',
        operation: 'subtract 6x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '3x + 2 = 17',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 2 from both sides',
        expression: '3x + 2 - 2 = 17 - 2',
        operation: 'subtract 2 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '3x = 15',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{15}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_09',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 4x + 13 = x + 28',
    latex: '4x + 13 = x + 28',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract x from both sides',
        expression: '4x - x + 13 = x - x + 28',
        operation: 'subtract x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '3x + 13 = 28',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 13 from both sides',
        expression: '3x + 13 - 13 = 28 - 13',
        operation: 'subtract 13 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '3x = 15',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{15}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_10',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 10x - 6 = 7x + 12',
    latex: '10x - 6 = 7x + 12',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 7x from both sides',
        expression: '10x - 7x - 6 = 7x - 7x + 12',
        operation: 'subtract 7x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '3x - 6 = 12',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 6 to both sides',
        expression: '3x - 6 + 6 = 12 + 6',
        operation: 'add 6 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '3x = 18',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{18}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_11',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 12x + 5 = 8x + 29',
    latex: '12x + 5 = 8x + 29',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 8x from both sides',
        expression: '12x - 8x + 5 = 8x - 8x + 29',
        operation: 'subtract 8x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '4x + 5 = 29',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 5 from both sides',
        expression: '4x + 5 - 5 = 29 - 5',
        operation: 'subtract 5 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '4x = 24',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 4',
        expression: '\\frac{4x}{4} = \\frac{24}{4}',
        operation: 'divide both sides by 4',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_12',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 3x - 8 = x + 14',
    latex: '3x - 8 = x + 14',
    answer: '11',
    answerLatex: 'x = 11',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract x from both sides',
        expression: '3x - x - 8 = x - x + 14',
        operation: 'subtract x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '2x - 8 = 14',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 8 to both sides',
        expression: '2x - 8 + 8 = 14 + 8',
        operation: 'add 8 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '2x = 22',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{22}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 11',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_13',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 11x - 7 = 6x + 18',
    latex: '11x - 7 = 6x + 18',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 6x from both sides',
        expression: '11x - 6x - 7 = 6x - 6x + 18',
        operation: 'subtract 6x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x - 7 = 18',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 7 to both sides',
        expression: '5x - 7 + 7 = 18 + 7',
        operation: 'add 7 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_14',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 15x + 4 = 10x + 34',
    latex: '15x + 4 = 10x + 34',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 10x from both sides',
        expression: '15x - 10x + 4 = 10x - 10x + 34',
        operation: 'subtract 10x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x + 4 = 34',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 4 from both sides',
        expression: '5x + 4 - 4 = 34 - 4',
        operation: 'subtract 4 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 30',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{30}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_15',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 13x - 9 = 8x + 16',
    latex: '13x - 9 = 8x + 16',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 8x from both sides',
        expression: '13x - 8x - 9 = 8x - 8x + 16',
        operation: 'subtract 8x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x - 9 = 16',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 9 to both sides',
        expression: '5x - 9 + 9 = 16 + 9',
        operation: 'add 9 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_16',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 5x + 12 = 2x + 30',
    latex: '5x + 12 = 2x + 30',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 2x from both sides',
        expression: '5x - 2x + 12 = 2x - 2x + 30',
        operation: 'subtract 2x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '3x + 12 = 30',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 12 from both sides',
        expression: '3x + 12 - 12 = 30 - 12',
        operation: 'subtract 12 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '3x = 18',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{18}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_17',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 14x - 3 = 9x + 22',
    latex: '14x - 3 = 9x + 22',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 9x from both sides',
        expression: '14x - 9x - 3 = 9x - 9x + 22',
        operation: 'subtract 9x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x - 3 = 22',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 3 to both sides',
        expression: '5x - 3 + 3 = 22 + 3',
        operation: 'add 3 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_18',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 3x + 20 = x + 36',
    latex: '3x + 20 = x + 36',
    answer: '8',
    answerLatex: 'x = 8',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract x from both sides',
        expression: '3x - x + 20 = x - x + 36',
        operation: 'subtract x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '2x + 20 = 36',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 20 from both sides',
        expression: '2x + 20 - 20 = 36 - 20',
        operation: 'subtract 20 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '2x = 16',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{16}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 8',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_19',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 16x + 1 = 11x + 26',
    latex: '16x + 1 = 11x + 26',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 11x from both sides',
        expression: '16x - 11x + 1 = 11x - 11x + 26',
        operation: 'subtract 11x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x + 1 = 26',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 1 from both sides',
        expression: '5x + 1 - 1 = 26 - 1',
        operation: 'subtract 1 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_20',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 9x - 11 = 4x + 14',
    latex: '9x - 11 = 4x + 14',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 4x from both sides',
        expression: '9x - 4x - 11 = 4x - 4x + 14',
        operation: 'subtract 4x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x - 11 = 14',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 11 to both sides',
        expression: '5x - 11 + 11 = 14 + 11',
        operation: 'add 11 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_21',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 17x + 8 = 12x + 38',
    latex: '17x + 8 = 12x + 38',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 12x from both sides',
        expression: '17x - 12x + 8 = 12x - 12x + 38',
        operation: 'subtract 12x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x + 8 = 38',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 8 from both sides',
        expression: '5x + 8 - 8 = 38 - 8',
        operation: 'subtract 8 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 30',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{30}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_22',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 6x + 14 = 3x + 32',
    latex: '6x + 14 = 3x + 32',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 3x from both sides',
        expression: '6x - 3x + 14 = 3x - 3x + 32',
        operation: 'subtract 3x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '3x + 14 = 32',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 14 from both sides',
        expression: '3x + 14 - 14 = 32 - 14',
        operation: 'subtract 14 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '3x = 18',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{18}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_23',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 18x - 4 = 13x + 21',
    latex: '18x - 4 = 13x + 21',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 13x from both sides',
        expression: '18x - 13x - 4 = 13x - 13x + 21',
        operation: 'subtract 13x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x - 4 = 21',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 4 to both sides',
        expression: '5x - 4 + 4 = 21 + 4',
        operation: 'add 4 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_24',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 7x + 19 = 3x + 47',
    latex: '7x + 19 = 3x + 47',
    answer: '7',
    answerLatex: 'x = 7',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 3x from both sides',
        expression: '7x - 3x + 19 = 3x - 3x + 47',
        operation: 'subtract 3x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '4x + 19 = 47',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 19 from both sides',
        expression: '4x + 19 - 19 = 47 - 19',
        operation: 'subtract 19 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '4x = 28',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 4',
        expression: '\\frac{4x}{4} = \\frac{28}{4}',
        operation: 'divide both sides by 4',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 7',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_25',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 20x - 6 = 15x + 19',
    latex: '20x - 6 = 15x + 19',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 15x from both sides',
        expression: '20x - 15x - 6 = 15x - 15x + 19',
        operation: 'subtract 15x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x - 6 = 19',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 6 to both sides',
        expression: '5x - 6 + 6 = 19 + 6',
        operation: 'add 6 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_26',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 4x + 25 = 2x + 45',
    latex: '4x + 25 = 2x + 45',
    answer: '10',
    answerLatex: 'x = 10',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 2x from both sides',
        expression: '4x - 2x + 25 = 2x - 2x + 45',
        operation: 'subtract 2x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '2x + 25 = 45',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 25 from both sides',
        expression: '2x + 25 - 25 = 45 - 25',
        operation: 'subtract 25 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '2x = 20',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{20}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 10',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_27',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 19x - 2 = 14x + 23',
    latex: '19x - 2 = 14x + 23',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 14x from both sides',
        expression: '19x - 14x - 2 = 14x - 14x + 23',
        operation: 'subtract 14x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x - 2 = 23',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Add 2 to both sides',
        expression: '5x - 2 + 2 = 23 + 2',
        operation: 'add 2 to both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_28',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 8x + 17 = 5x + 35',
    latex: '8x + 17 = 5x + 35',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 5x from both sides',
        expression: '8x - 5x + 17 = 5x - 5x + 35',
        operation: 'subtract 5x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '3x + 17 = 35',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 17 from both sides',
        expression: '3x + 17 - 17 = 35 - 17',
        operation: 'subtract 17 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '3x = 18',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{18}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_29',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 21x + 6 = 16x + 31',
    latex: '21x + 6 = 16x + 31',
    answer: '5',
    answerLatex: 'x = 5',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 16x from both sides',
        expression: '21x - 16x + 6 = 16x - 16x + 31',
        operation: 'subtract 16x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '5x + 6 = 31',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 6 from both sides',
        expression: '5x + 6 - 6 = 31 - 6',
        operation: 'subtract 6 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '5x = 25',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 5',
        expression: '\\frac{5x}{5} = \\frac{25}{5}',
        operation: 'divide both sides by 5',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 5',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },
  {
    id: 'le_hard_30',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 5x + 22 = 3x + 40',
    latex: '5x + 22 = 3x + 40',
    answer: '9',
    answerLatex: 'x = 9',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Subtract 3x from both sides',
        expression: '5x - 3x + 22 = 3x - 3x + 40',
        operation: 'subtract 3x from both sides',
      },
      {
        stepNumber: 2,
        description: 'Simplify',
        expression: '2x + 22 = 40',
        operation: 'simplify',
      },
      {
        stepNumber: 3,
        description: 'Subtract 22 from both sides',
        expression: '2x + 22 - 22 = 40 - 22',
        operation: 'subtract 22 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '2x = 18',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{18}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 9',
        operation: 'simplify',
      },
    ],
    tags: ['multi-step', 'variables-both-sides'],
  },

  // ==================== VERY HARD - Problems with distribution and complex multi-step (10 problems) ====================
  {
    id: 'le_veryhard_01',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 2(x + 3) = 14',
    latex: '2(x + 3) = 14',
    answer: '4',
    answerLatex: 'x = 4',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Distribute 2',
        expression: '2x + 6 = 14',
        operation: 'distribute',
      },
      {
        stepNumber: 2,
        description: 'Subtract 6 from both sides',
        expression: '2x + 6 - 6 = 14 - 6',
        operation: 'subtract 6 from both sides',
      },
      {
        stepNumber: 3,
        description: 'Simplify',
        expression: '2x = 8',
        operation: 'simplify',
      },
      {
        stepNumber: 4,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{8}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 5,
        description: 'Simplify',
        expression: 'x = 4',
        operation: 'simplify',
      },
    ],
    tags: ['very-hard', 'distribution', 'parentheses'],
  },
  {
    id: 'le_veryhard_02',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 3(x - 4) = 15',
    latex: '3(x - 4) = 15',
    answer: '9',
    answerLatex: 'x = 9',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Distribute 3',
        expression: '3x - 12 = 15',
        operation: 'distribute',
      },
      {
        stepNumber: 2,
        description: 'Add 12 to both sides',
        expression: '3x - 12 + 12 = 15 + 12',
        operation: 'add 12 to both sides',
      },
      {
        stepNumber: 3,
        description: 'Simplify',
        expression: '3x = 27',
        operation: 'simplify',
      },
      {
        stepNumber: 4,
        description: 'Divide both sides by 3',
        expression: '\\frac{3x}{3} = \\frac{27}{3}',
        operation: 'divide both sides by 3',
      },
      {
        stepNumber: 5,
        description: 'Simplify',
        expression: 'x = 9',
        operation: 'simplify',
      },
    ],
    tags: ['very-hard', 'distribution', 'parentheses'],
  },
  {
    id: 'le_veryhard_03',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 4(x + 2) = 2x + 20',
    latex: '4(x + 2) = 2x + 20',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Distribute 4',
        expression: '4x + 8 = 2x + 20',
        operation: 'distribute',
      },
      {
        stepNumber: 2,
        description: 'Subtract 2x from both sides',
        expression: '4x - 2x + 8 = 2x - 2x + 20',
        operation: 'subtract 2x from both sides',
      },
      {
        stepNumber: 3,
        description: 'Simplify',
        expression: '2x + 8 = 20',
        operation: 'simplify',
      },
      {
        stepNumber: 4,
        description: 'Subtract 8 from both sides',
        expression: '2x + 8 - 8 = 20 - 8',
        operation: 'subtract 8 from both sides',
      },
      {
        stepNumber: 5,
        description: 'Simplify',
        expression: '2x = 12',
        operation: 'simplify',
      },
      {
        stepNumber: 6,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{12}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 7,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['very-hard', 'distribution', 'parentheses', 'variables-both-sides'],
  },
  {
    id: 'le_veryhard_04',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 5(x - 3) = 3x + 7',
    latex: '5(x - 3) = 3x + 7',
    answer: '11',
    answerLatex: 'x = 11',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Distribute 5',
        expression: '5x - 15 = 3x + 7',
        operation: 'distribute',
      },
      {
        stepNumber: 2,
        description: 'Subtract 3x from both sides',
        expression: '5x - 3x - 15 = 3x - 3x + 7',
        operation: 'subtract 3x from both sides',
      },
      {
        stepNumber: 3,
        description: 'Simplify',
        expression: '2x - 15 = 7',
        operation: 'simplify',
      },
      {
        stepNumber: 4,
        description: 'Add 15 to both sides',
        expression: '2x - 15 + 15 = 7 + 15',
        operation: 'add 15 to both sides',
      },
      {
        stepNumber: 5,
        description: 'Simplify',
        expression: '2x = 22',
        operation: 'simplify',
      },
      {
        stepNumber: 6,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{22}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 7,
        description: 'Simplify',
        expression: 'x = 11',
        operation: 'simplify',
      },
    ],
    tags: ['very-hard', 'distribution', 'parentheses', 'variables-both-sides'],
  },
  {
    id: 'le_veryhard_05',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 2(x + 5) + 3 = 19',
    latex: '2(x + 5) + 3 = 19',
    answer: '3',
    answerLatex: 'x = 3',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Distribute 2',
        expression: '2x + 10 + 3 = 19',
        operation: 'distribute',
      },
      {
        stepNumber: 2,
        description: 'Combine like terms',
        expression: '2x + 13 = 19',
        operation: 'combine like terms',
      },
      {
        stepNumber: 3,
        description: 'Subtract 13 from both sides',
        expression: '2x + 13 - 13 = 19 - 13',
        operation: 'subtract 13 from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '2x = 6',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{6}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 3',
        operation: 'simplify',
      },
    ],
    tags: ['very-hard', 'distribution', 'parentheses', 'combining-terms'],
  },
  {
    id: 'le_veryhard_06',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 3(2x - 1) = 4x + 9',
    latex: '3(2x - 1) = 4x + 9',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Distribute 3',
        expression: '6x - 3 = 4x + 9',
        operation: 'distribute',
      },
      {
        stepNumber: 2,
        description: 'Subtract 4x from both sides',
        expression: '6x - 4x - 3 = 4x - 4x + 9',
        operation: 'subtract 4x from both sides',
      },
      {
        stepNumber: 3,
        description: 'Simplify',
        expression: '2x - 3 = 9',
        operation: 'simplify',
      },
      {
        stepNumber: 4,
        description: 'Add 3 to both sides',
        expression: '2x - 3 + 3 = 9 + 3',
        operation: 'add 3 to both sides',
      },
      {
        stepNumber: 5,
        description: 'Simplify',
        expression: '2x = 12',
        operation: 'simplify',
      },
      {
        stepNumber: 6,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{12}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 7,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['very-hard', 'distribution', 'parentheses', 'variables-both-sides'],
  },
  {
    id: 'le_veryhard_07',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 2(3x + 4) = 5x + 17',
    latex: '2(3x + 4) = 5x + 17',
    answer: '9',
    answerLatex: 'x = 9',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Distribute 2',
        expression: '6x + 8 = 5x + 17',
        operation: 'distribute',
      },
      {
        stepNumber: 2,
        description: 'Subtract 5x from both sides',
        expression: '6x - 5x + 8 = 5x - 5x + 17',
        operation: 'subtract 5x from both sides',
      },
      {
        stepNumber: 3,
        description: 'Simplify',
        expression: 'x + 8 = 17',
        operation: 'simplify',
      },
      {
        stepNumber: 4,
        description: 'Subtract 8 from both sides',
        expression: 'x + 8 - 8 = 17 - 8',
        operation: 'subtract 8 from both sides',
      },
      {
        stepNumber: 5,
        description: 'Simplify',
        expression: 'x = 9',
        operation: 'simplify',
      },
    ],
    tags: ['very-hard', 'distribution', 'parentheses', 'variables-both-sides'],
  },
  {
    id: 'le_veryhard_08',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 4(x - 2) - 3 = 2x + 5',
    latex: '4(x - 2) - 3 = 2x + 5',
    answer: '8',
    answerLatex: 'x = 8',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Distribute 4',
        expression: '4x - 8 - 3 = 2x + 5',
        operation: 'distribute',
      },
      {
        stepNumber: 2,
        description: 'Combine like terms',
        expression: '4x - 11 = 2x + 5',
        operation: 'combine like terms',
      },
      {
        stepNumber: 3,
        description: 'Subtract 2x from both sides',
        expression: '4x - 2x - 11 = 2x - 2x + 5',
        operation: 'subtract 2x from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '2x - 11 = 5',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Add 11 to both sides',
        expression: '2x - 11 + 11 = 5 + 11',
        operation: 'add 11 to both sides',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: '2x = 16',
        operation: 'simplify',
      },
      {
        stepNumber: 7,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{16}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 8,
        description: 'Simplify',
        expression: 'x = 8',
        operation: 'simplify',
      },
    ],
    tags: ['very-hard', 'distribution', 'parentheses', 'combining-terms', 'variables-both-sides'],
  },
  {
    id: 'le_veryhard_09',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 3(x + 4) = 2(x + 9)',
    latex: '3(x + 4) = 2(x + 9)',
    answer: '6',
    answerLatex: 'x = 6',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Distribute 3 on left side',
        expression: '3x + 12 = 2(x + 9)',
        operation: 'distribute',
      },
      {
        stepNumber: 2,
        description: 'Distribute 2 on right side',
        expression: '3x + 12 = 2x + 18',
        operation: 'distribute',
      },
      {
        stepNumber: 3,
        description: 'Subtract 2x from both sides',
        expression: '3x - 2x + 12 = 2x - 2x + 18',
        operation: 'subtract 2x from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: 'x + 12 = 18',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Subtract 12 from both sides',
        expression: 'x + 12 - 12 = 18 - 12',
        operation: 'subtract 12 from both sides',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: 'x = 6',
        operation: 'simplify',
      },
    ],
    tags: ['very-hard', 'distribution', 'parentheses-both-sides', 'variables-both-sides'],
  },
  {
    id: 'le_veryhard_10',
    category: ProblemCategory.LINEAR_EQUATIONS,
    difficulty: ProblemDifficulty.HARD,
    text: 'Solve for x: 5(x - 2) = 3(x + 4)',
    latex: '5(x - 2) = 3(x + 4)',
    answer: '11',
    answerLatex: 'x = 11',
    expectedSteps: [
      {
        stepNumber: 1,
        description: 'Distribute 5 on left side',
        expression: '5x - 10 = 3(x + 4)',
        operation: 'distribute',
      },
      {
        stepNumber: 2,
        description: 'Distribute 3 on right side',
        expression: '5x - 10 = 3x + 12',
        operation: 'distribute',
      },
      {
        stepNumber: 3,
        description: 'Subtract 3x from both sides',
        expression: '5x - 3x - 10 = 3x - 3x + 12',
        operation: 'subtract 3x from both sides',
      },
      {
        stepNumber: 4,
        description: 'Simplify',
        expression: '2x - 10 = 12',
        operation: 'simplify',
      },
      {
        stepNumber: 5,
        description: 'Add 10 to both sides',
        expression: '2x - 10 + 10 = 12 + 10',
        operation: 'add 10 to both sides',
      },
      {
        stepNumber: 6,
        description: 'Simplify',
        expression: '2x = 22',
        operation: 'simplify',
      },
      {
        stepNumber: 7,
        description: 'Divide both sides by 2',
        expression: '\\frac{2x}{2} = \\frac{22}{2}',
        operation: 'divide both sides by 2',
      },
      {
        stepNumber: 8,
        description: 'Simplify',
        expression: 'x = 11',
        operation: 'simplify',
      },
    ],
    tags: ['very-hard', 'distribution', 'parentheses-both-sides', 'variables-both-sides'],
  },
];

/**
 * Get problem by ID
 *
 * @param id - Problem ID
 * @returns Problem or undefined if not found
 */
export const getProblemById = (id: string): Problem | undefined => {
  return LINEAR_EQUATION_PROBLEMS.find(p => p.id === id);
};

/**
 * Get problems by difficulty
 *
 * @param difficulty - Difficulty level to filter by
 * @returns Array of problems matching the difficulty
 */
export const getProblemsByDifficulty = (
  difficulty: ProblemDifficulty
): Problem[] => {
  return LINEAR_EQUATION_PROBLEMS.filter(p => p.difficulty === difficulty);
};

/**
 * Get random problem
 *
 * @param difficulty - Optional difficulty filter
 * @returns Random problem from the library
 */
export const getRandomProblem = (
  difficulty?: ProblemDifficulty
): Problem => {
  const problems = difficulty
    ? getProblemsByDifficulty(difficulty)
    : LINEAR_EQUATION_PROBLEMS;

  const randomIndex = Math.floor(Math.random() * problems.length);
  return problems[randomIndex];
};

/**
 * Get next problem in sequence
 *
 * @param currentId - ID of current problem
 * @returns Next problem or null if at end
 */
export const getNextProblem = (currentId: string): Problem | null => {
  const currentIndex = LINEAR_EQUATION_PROBLEMS.findIndex(p => p.id === currentId);
  if (currentIndex === -1 || currentIndex === LINEAR_EQUATION_PROBLEMS.length - 1) {
    return null;
  }
  return LINEAR_EQUATION_PROBLEMS[currentIndex + 1];
};

/**
 * Get previous problem in sequence
 *
 * @param currentId - ID of current problem
 * @returns Previous problem or null if at beginning
 */
export const getPreviousProblem = (currentId: string): Problem | null => {
  const currentIndex = LINEAR_EQUATION_PROBLEMS.findIndex(p => p.id === currentId);
  if (currentIndex <= 0) {
    return null;
  }
  return LINEAR_EQUATION_PROBLEMS[currentIndex - 1];
};

/**
 * Get total number of problems
 *
 * @returns Total problem count
 */
export const getTotalProblems = (): number => {
  return LINEAR_EQUATION_PROBLEMS.length;
};

/**
 * Get problem statistics
 *
 * @returns Statistics about the problem library
 */
export const getProblemStats = () => {
  const easy = getProblemsByDifficulty(ProblemDifficulty.EASY).length;
  const medium = getProblemsByDifficulty(ProblemDifficulty.MEDIUM).length;
  const hard = getProblemsByDifficulty(ProblemDifficulty.HARD).length;

  return {
    total: LINEAR_EQUATION_PROBLEMS.length,
    easy,
    medium,
    hard,
  };
};
